"""empty message

Revision ID: ce2cca496c24
Revises: 053d3b1f19e9
Create Date: 2020-05-01 10:58:56.611857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce2cca496c24'
down_revision = '053d3b1f19e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('team1', sa.String(length=255), nullable=True),
    sa.Column('team2', sa.String(length=255), nullable=True),
    sa.Column('toss_winner', sa.String(length=255), nullable=True),
    sa.Column('toss_decision', sa.String(length=255), nullable=True),
    sa.Column('result', sa.String(length=255), nullable=True),
    sa.Column('dl_applied', sa.Integer(), nullable=True),
    sa.Column('winner', sa.String(length=255), nullable=True),
    sa.Column('win_by_runs', sa.Integer(), nullable=True),
    sa.Column('win_by_wickets', sa.Integer(), nullable=True),
    sa.Column('player_of_match', sa.String(length=255), nullable=True),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('umpire1', sa.String(length=255), nullable=True),
    sa.Column('umpire2', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('inning', sa.Integer(), nullable=True),
    sa.Column('batting_team', sa.String(length=255), nullable=True),
    sa.Column('bowing_team', sa.String(length=255), nullable=True),
    sa.Column('over', sa.Integer(), nullable=True),
    sa.Column('ball', sa.Integer(), nullable=True),
    sa.Column('batsman', sa.String(length=255), nullable=True),
    sa.Column('non_striker', sa.String(length=255), nullable=True),
    sa.Column('bowler', sa.String(length=255), nullable=True),
    sa.Column('is_super_over', sa.Boolean(), nullable=True),
    sa.Column('wide_runs', sa.Integer(), nullable=True),
    sa.Column('bye_runs', sa.Integer(), nullable=True),
    sa.Column('legbye_runs', sa.Integer(), nullable=True),
    sa.Column('noball_runs', sa.Integer(), nullable=True),
    sa.Column('penalty_runs', sa.Integer(), nullable=True),
    sa.Column('batsman_runs', sa.Integer(), nullable=True),
    sa.Column('extra_runs', sa.Integer(), nullable=True),
    sa.Column('total_runs', sa.Integer(), nullable=True),
    sa.Column('player_dismissed', sa.String(length=255), nullable=True),
    sa.Column('dismissal_kind', sa.String(length=255), nullable=True),
    sa.Column('filder', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deliveries')
    op.drop_table('match')
    # ### end Alembic commands ###
